name: "my first pod"
containers:
  - name: "hello world"
    image: "ubuntu"
    command: echo
    args:
      - "hello world"
  - name: "bang"
    image: "ubuntu"
    command: echo
    args:
      - "bang"
  - name: "whimper"
    image: "ubuntu"
    command: echo
    args:
      - "whimper"